import * as Icons from 'mdue';

import { Icon } from '../../data-model/generic/icon';

export const icons = new Map<string, Icon>([
    ['access-point', new Icon(Icons.AccessPoint)],
    ['account-circle', new Icon(Icons.AccountCircle)],
    ['account-box-multiple', new Icon(Icons.AccountBoxMultiple)],
    ['account-cowboy-hat', new Icon(Icons.AccountCowboyHat)],
    ['account-star', new Icon(Icons.AccountStar)],
    ['account-tie', new Icon(Icons.AccountTie)],
    ['airplane', new Icon(Icons.Airplane)],
    ['alarm-light', new Icon(Icons.AlarmLight)],
    ['alert-circle', new Icon(Icons.AlertCircle)],
    ['alien', new Icon(Icons.Alien)],
    ['ambulance', new Icon(Icons.Ambulance)],
    ['ammunition', new Icon(Icons.Ammunition)],
    ['archive', new Icon(Icons.Archive)],
    ['arm-flex', new Icon(Icons.ArmFlex)],
    ['arrow-right-drop-circle', new Icon(Icons.ArrowRightDropCircle)],
    ['baseball-bat', new Icon(Icons.BaseballBat)],
    ['bed', new Icon(Icons.Bed)],
    ['bomb', new Icon(Icons.Bomb)],
    ['bookmark', new Icon(Icons.Bookmark)],
    ['briefcase', new Icon(Icons.Briefcase)],
    ['broom', new Icon(Icons.Broom)],
    ['bus', new Icon(Icons.Bus)],
    ['cake-variant', new Icon(Icons.CakeVariant)],
    ['cards-heart', new Icon(Icons.CardsHeart)],
    ['cart', new Icon(Icons.Cart)],
    ['cat', new Icon(Icons.Cat)],
    ['chat', new Icon(Icons.Chat)],
    ['check-decagram', new Icon(Icons.CheckDecagram)],
    ['circle-slice-8', new Icon(Icons.CircleSlice_8, true)],
    ['code-braces', new Icon(Icons.CodeBraces)],
    ['coffee', new Icon(Icons.Coffee)],
    ['emoticon', new Icon(Icons.Emoticon)],
    ['face', new Icon(Icons.Face)],
    ['faceWoman', new Icon(Icons.FaceWoman)],
    ['flag-variant', new Icon(Icons.FlagVariant)],
    ['food-drumstick', new Icon(Icons.FoodDrumstick)],
    ['ghost', new Icon(Icons.Ghost)],
    ['home', new Icon(Icons.Home)],
    ['label', new Icon(Icons.Label)],
    ['map-marker', new Icon(Icons.MapMarker)],
    ['microsoft-xbox-controller', new Icon(Icons.MicrosoftXboxController)],
    ['monitor', new Icon(Icons.Monitor)],
    ['movie-open', new Icon(Icons.MovieOpen)],
    ['music', new Icon(Icons.Music)],
    ['nature-people', new Icon(Icons.NaturePeople)],
    ['phone', new Icon(Icons.Phone)],
    ['sofa-single', new Icon(Icons.SofaSingle)],
    ['star', new Icon(Icons.Star)],
    ['thumb-down', new Icon(Icons.ThumbDown)],
    ['thumb-up', new Icon(Icons.ThumbUp)],
    ['web', new Icon(Icons.Web)]
]);
